
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class CrearUserGUI extends javax.swing.JFrame {

    /**
     * Creates new form CrearUserGUI
     */
    public CrearUserGUI() {
        initComponents();
    }

    
    public static String Nombre; 
    public static String username;
    public static int age;
    public static String password;
    public static String tipoUser="";
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        NombreComp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomUsuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Contra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ADMINISTRADOR = new javax.swing.JToggleButton();
        CONTENIDOS = new javax.swing.JToggleButton();
        LIMITADO = new javax.swing.JToggleButton();
        Edad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CREATED = new javax.swing.JButton();
        BACK2MENU = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreCompActionPerformed(evt);
            }
        });
        jPanel1.add(NombreComp, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 290, -1));

        jLabel1.setText("Nombre Completo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 110, -1));

        NomUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(NomUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 290, -1));

        jLabel2.setText("Nombre de Usuario");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 110, -1));

        Contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraActionPerformed(evt);
            }
        });
        jPanel1.add(Contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 290, -1));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 110, -1));

        ADMINISTRADOR.setText("Administrador");
        ADMINISTRADOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADMINISTRADORActionPerformed(evt);
            }
        });
        jPanel1.add(ADMINISTRADOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        CONTENIDOS.setText("Contenidos");
        CONTENIDOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTENIDOSActionPerformed(evt);
            }
        });
        jPanel1.add(CONTENIDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, -1, -1));

        LIMITADO.setText("Limitado");
        LIMITADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LIMITADOActionPerformed(evt);
            }
        });
        jPanel1.add(LIMITADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, -1, -1));

        Edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadActionPerformed(evt);
            }
        });
        jPanel1.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 290, -1));

        jLabel4.setText("Edad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 110, -1));

        CREATED.setText("Continuar");
        CREATED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEDActionPerformed(evt);
            }
        });
        jPanel1.add(CREATED, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 410, -1, -1));

        BACK2MENU.setText("Salir");
        BACK2MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2MENUActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, -1, -1));

        jLabel5.setText("Crear Usuario");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NombreCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreCompActionPerformed
        
    }//GEN-LAST:event_NombreCompActionPerformed

    private void ADMINISTRADORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADMINISTRADORActionPerformed
      tipoUser = "admin";     
       
    }//GEN-LAST:event_ADMINISTRADORActionPerformed

    private void CREATEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEDActionPerformed
 
       
        if(NombreComp.getText().isEmpty()||NomUsuario.getText().isEmpty()||Contra.getText().isEmpty()||Edad.getText().isEmpty()||tipoUser.equals("")){
           JOptionPane.showMessageDialog(rootPane, "Llene todos los campos de informacion");
        
     
        }else{
            Nombre =NombreComp.getText();
            username =NomUsuario.getText();
            password = Contra.getText();
            age = Integer.parseInt(Edad.getText());
            Heaven.CrearUsuario(Nombre, username, password, age);
        
        //Mensaje de exito
         JOptionPane.showMessageDialog(rootPane, "Usuario creado exitosamente");
        this.setVisible(false);
        Menu m = new Menu();
        m.setVisible(true);
         System.out.println(Heaven.cuentas.get(0));
        }
    }//GEN-LAST:event_CREATEDActionPerformed

    private void CONTENIDOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTENIDOSActionPerformed
         tipoUser = "contenidos";   
    }//GEN-LAST:event_CONTENIDOSActionPerformed

    private void LIMITADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LIMITADOActionPerformed
         tipoUser = "limitado";   
    }//GEN-LAST:event_LIMITADOActionPerformed

    private void NomUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomUsuarioActionPerformed

    private void ContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraActionPerformed

    private void EdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadActionPerformed

    private void BACK2MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2MENUActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACK2MENUActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearUserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearUserGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton ADMINISTRADOR;
    private javax.swing.JButton BACK2MENU;
    private javax.swing.JToggleButton CONTENIDOS;
    private javax.swing.JButton CREATED;
    private javax.swing.JTextField Contra;
    private javax.swing.JTextField Edad;
    private javax.swing.JToggleButton LIMITADO;
    private javax.swing.JTextField NomUsuario;
    private javax.swing.JTextField NombreComp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
