
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class CrearEventoDeportivoGUI extends javax.swing.JFrame {

    /**
     * Creates new form CrearEventoGUI
     */
    public CrearEventoDeportivoGUI() {
        initComponents();
    }
      static int year;
      static int month;
      static int day;
      static int code;
      static double monto;
      static String titulo;
      static int cantidad;
      static String team1, team2;
      static String tipoSport;
      static String desc;
      static String autor;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TITULO = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DESCRIPCION = new javax.swing.JTextArea();
        BACK2TYPESELECC = new javax.swing.JButton();
        EVENTCREATED = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CANTIDAD = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TEAM2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TEAM1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        FUTBOL = new javax.swing.JButton();
        TENIS = new javax.swing.JButton();
        RUGBY = new javax.swing.JButton();
        BASEBALL = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        FechaSelecc = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        MONTO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Codigo del evento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));

        CODIGO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CODIGOActionPerformed(evt);
            }
        });
        jPanel1.add(CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, -1));

        jLabel3.setText("Titulo del evento");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 110, 30));
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 240, -1));

        jLabel4.setText("Descripcion");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 90, 30));

        DESCRIPCION.setColumns(20);
        DESCRIPCION.setRows(5);
        jScrollPane1.setViewportView(DESCRIPCION);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 630, 220));

        BACK2TYPESELECC.setText("Salir");
        BACK2TYPESELECC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2TYPESELECCActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2TYPESELECC, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        EVENTCREATED.setText("Crear Evento");
        EVENTCREATED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTCREATEDActionPerformed(evt);
            }
        });
        jPanel1.add(EVENTCREATED, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        jLabel2.setText("EVENTO DEPORTIVO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jLabel5.setText("Cantidad de personas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 30));
        jPanel1.add(CANTIDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 240, -1));

        jLabel6.setText("Equipo 2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 50, 40));
        jPanel1.add(TEAM2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, 170, -1));

        jLabel7.setText("Equipos");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 50, 40));

        jLabel8.setText("Equipo 1");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 50, 40));
        jPanel1.add(TEAM1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 170, -1));

        jLabel9.setText("Tipo de Deporte");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 150, -1, -1));

        FUTBOL.setText("FUTBOL");
        FUTBOL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FUTBOLActionPerformed(evt);
            }
        });
        jPanel1.add(FUTBOL, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, -1, -1));

        TENIS.setText("TENIS");
        TENIS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TENISActionPerformed(evt);
            }
        });
        jPanel1.add(TENIS, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, -1, -1));

        RUGBY.setText("RUGBY");
        RUGBY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUGBYActionPerformed(evt);
            }
        });
        jPanel1.add(RUGBY, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 190, -1, -1));

        BASEBALL.setText("BASEBALL");
        BASEBALL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BASEBALLActionPerformed(evt);
            }
        });
        jPanel1.add(BASEBALL, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, -1, -1));

        jLabel10.setText("Datos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel11.setText("Fecha");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 50, -1));
        jPanel1.add(FechaSelecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 180, -1));

        jLabel12.setText("Renta");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 70, 30));

        MONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTOActionPerformed(evt);
            }
        });
        jPanel1.add(MONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 240, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BACK2TYPESELECCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2TYPESELECCActionPerformed
        SeleccionTipoEventoGUI event = new  SeleccionTipoEventoGUI();
        event.setVisible(true);
        this.dispose();
        
        
        
    
        
        
    }//GEN-LAST:event_BACK2TYPESELECCActionPerformed

    private void EVENTCREATEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTCREATEDActionPerformed
        Date fecha = FechaSelecc.getDate();
        
         year = fecha.getYear()+1900;
        month = fecha.getMonth();
         day = fecha.getDay();
         
       code = Integer.parseInt(CODIGO.getText());
       titulo=TITULO.getText();
      cantidad = Integer.parseInt(CANTIDAD.getText());
      team1 = TEAM1.getText();
      team2 = TEAM2.getText();
      desc= DESCRIPCION.getText();
      monto =Double.parseDouble(MONTO.getText());
      autor = Login.user;
      
       Heaven.CrearSport(code, titulo, desc, monto, autor, cantidad, tipoSport, day, month, year);
      
         JOptionPane.showMessageDialog(rootPane, "Evento creado exitosamente");
         SeleccionTipoEventoGUI selecc = new SeleccionTipoEventoGUI();
         selecc.setVisible(true);
         selecc.setLocationRelativeTo(null);
        this.dispose();
        System.out.println(autor);

     
    }//GEN-LAST:event_EVENTCREATEDActionPerformed

    private void CODIGOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CODIGOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CODIGOActionPerformed

    private void FUTBOLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FUTBOLActionPerformed
          tipoSport ="futbol";
    }//GEN-LAST:event_FUTBOLActionPerformed

    private void TENISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TENISActionPerformed
        tipoSport ="tenis";
    }//GEN-LAST:event_TENISActionPerformed

    private void RUGBYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUGBYActionPerformed
       tipoSport ="rugby";
    }//GEN-LAST:event_RUGBYActionPerformed

    private void BASEBALLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BASEBALLActionPerformed
        tipoSport ="baseball";
    }//GEN-LAST:event_BASEBALLActionPerformed

    private void MONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEventoDeportivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEventoDeportivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEventoDeportivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEventoDeportivoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEventoDeportivoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK2TYPESELECC;
    private javax.swing.JButton BASEBALL;
    private javax.swing.JTextField CANTIDAD;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextArea DESCRIPCION;
    private javax.swing.JButton EVENTCREATED;
    private javax.swing.JButton FUTBOL;
    private com.toedter.calendar.JDateChooser FechaSelecc;
    private javax.swing.JTextField MONTO;
    private javax.swing.JButton RUGBY;
    private javax.swing.JTextField TEAM1;
    private javax.swing.JTextField TEAM2;
    private javax.swing.JButton TENIS;
    private javax.swing.JTextField TITULO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
