
import java.util.Date;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class CrearEventoReligiosoGUI extends javax.swing.JFrame {

    /**
     * Creates new form CrearEventoReligiosoGUI
     */
    public CrearEventoReligiosoGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CODIGO = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TITULO = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        DESCRIPCION = new javax.swing.JTextArea();
        BACK2TYPESELECC1 = new javax.swing.JButton();
        EVENTCREATED = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        CANTPERSONAS = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fechitaReligiosa = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        MONTO = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("EVENTO RELIGIOSO");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel6.setText("Codigo del evento");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 30));
        jPanel1.add(CODIGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 240, -1));

        jLabel7.setText("Titulo del evento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 110, 30));
        jPanel1.add(TITULO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 240, -1));

        jLabel8.setText("Descripcion");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 330, 90, 30));

        DESCRIPCION.setColumns(20);
        DESCRIPCION.setRows(5);
        jScrollPane2.setViewportView(DESCRIPCION);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 630, 220));

        BACK2TYPESELECC1.setText("Salir");
        BACK2TYPESELECC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2TYPESELECC1ActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2TYPESELECC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        EVENTCREATED.setText("Crear Evento");
        EVENTCREATED.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTCREATEDActionPerformed(evt);
            }
        });
        jPanel1.add(EVENTCREATED, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 530, -1, -1));

        jLabel12.setText("Cantidad de personas");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 130, 30));
        jPanel1.add(CANTPERSONAS, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 240, -1));

        jLabel14.setText("Datos");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));
        jPanel1.add(fechitaReligiosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 180, -1));

        jLabel1.setText("Fecha");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 50, -1));

        jLabel13.setText("Renta");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 70, 30));

        MONTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MONTOActionPerformed(evt);
            }
        });
        jPanel1.add(MONTO, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 240, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 965, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     static int year;
      static int month;
      static int day;
      static int code;
      static double monto;
      static String titulo;
      static int cantidad;
      static String tipoMusic;
      static String desc;
      static String autor;
    
    
    private void BACK2TYPESELECC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2TYPESELECC1ActionPerformed
        SeleccionTipoEventoGUI event = new  SeleccionTipoEventoGUI();
        event.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACK2TYPESELECC1ActionPerformed

    private void EVENTCREATEDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTCREATEDActionPerformed
         Date fecha = fechitaReligiosa.getDate();
        
         year = fecha.getYear()+1900;
        month = fecha.getMonth();
         day = fecha.getDay();
         
      code = Integer.parseInt(CODIGO.getText());
      titulo=TITULO.getText();
      cantidad = Integer.parseInt(CANTPERSONAS.getText());
      desc= DESCRIPCION.getText();
      monto =Double.parseDouble(MONTO.getText());
      autor = Login.user;
      
        Heaven.CrearReligioso(code, titulo, desc, monto, autor,  cantidad, day, month, year);
      
         JOptionPane.showMessageDialog(rootPane, "Evento creado exitosamente");
         SeleccionTipoEventoGUI selecc = new SeleccionTipoEventoGUI();
         selecc.setVisible(true);
         selecc.setLocationRelativeTo(null);
        this.dispose();
        System.out.println(autor);
    }//GEN-LAST:event_EVENTCREATEDActionPerformed

    private void MONTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MONTOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MONTOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEventoReligiosoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEventoReligiosoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEventoReligiosoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEventoReligiosoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEventoReligiosoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK2TYPESELECC1;
    private javax.swing.JTextField CANTPERSONAS;
    private javax.swing.JTextField CODIGO;
    private javax.swing.JTextArea DESCRIPCION;
    private javax.swing.JButton EVENTCREATED;
    private javax.swing.JTextField MONTO;
    private javax.swing.JTextField TITULO;
    private com.toedter.calendar.JDateChooser fechitaReligiosa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
