
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class EventsManager extends javax.swing.JFrame {

    /**
     * Creates new form EventsManager
     */
    public EventsManager() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CREATEeVENT = new javax.swing.JButton();
        BACK2MENU = new javax.swing.JButton();
        VIEWEVENT = new javax.swing.JButton();
        DELETE1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CREATEeVENT.setText("Crear Evento");
        CREATEeVENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREATEeVENTActionPerformed(evt);
            }
        });
        jPanel1.add(CREATEeVENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 130, 50));

        BACK2MENU.setText("Salir");
        BACK2MENU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2MENUActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2MENU, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, -1, -1));

        VIEWEVENT.setText("Ver Evento");
        VIEWEVENT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VIEWEVENTActionPerformed(evt);
            }
        });
        jPanel1.add(VIEWEVENT, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 130, 50));

        DELETE1.setText("Eliminar Evento");
        DELETE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DELETE1ActionPerformed(evt);
            }
        });
        jPanel1.add(DELETE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 130, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CREATEeVENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREATEeVENTActionPerformed
       SeleccionTipoEventoGUI evento = new SeleccionTipoEventoGUI();
       evento.setVisible(true);
       evento.setLocationRelativeTo(null);
       this.dispose();
           
       
    }//GEN-LAST:event_CREATEeVENTActionPerformed

    private void BACK2MENUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2MENUActionPerformed
        Menu m = new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BACK2MENUActionPerformed

    private void VIEWEVENTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VIEWEVENTActionPerformed
          
    }//GEN-LAST:event_VIEWEVENTActionPerformed

    private void DELETE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DELETE1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DELETE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EventsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EventsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EventsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EventsManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EventsManager().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK2MENU;
    private javax.swing.JButton CREATEeVENT;
    private javax.swing.JButton DELETE1;
    private javax.swing.JButton VIEWEVENT;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
