/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Josue Gavidia
 */
public class SeleccionTipoEventoGUI extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionTipoEventoGUI
     */
    public SeleccionTipoEventoGUI() {
        initComponents();
    }
     
    public static String tipoEvento="";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        EVENTORELIGIOSO = new javax.swing.JButton();
        EVENTODEPORTIVO = new javax.swing.JButton();
        EVENTOMUSICAL = new javax.swing.JButton();
        BACK2EVENTSMANAGER = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EVENTORELIGIOSO.setText("Religioso");
        EVENTORELIGIOSO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTORELIGIOSOActionPerformed(evt);
            }
        });
        jPanel1.add(EVENTORELIGIOSO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 160, 50));

        EVENTODEPORTIVO.setText("Deportivo");
        EVENTODEPORTIVO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTODEPORTIVOActionPerformed(evt);
            }
        });
        jPanel1.add(EVENTODEPORTIVO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, 50));

        EVENTOMUSICAL.setText("Musical");
        EVENTOMUSICAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTOMUSICALActionPerformed(evt);
            }
        });
        jPanel1.add(EVENTOMUSICAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 160, 50));

        BACK2EVENTSMANAGER.setText("Salir");
        BACK2EVENTSMANAGER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BACK2EVENTSMANAGERActionPerformed(evt);
            }
        });
        jPanel1.add(BACK2EVENTSMANAGER, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EVENTODEPORTIVOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTODEPORTIVOActionPerformed
        tipoEvento = "deportivo";
        CrearEventoDeportivoGUI create = new  CrearEventoDeportivoGUI();
        create.setVisible(true);
        create.setLocationRelativeTo(null);
          this.setVisible(false);
    }//GEN-LAST:event_EVENTODEPORTIVOActionPerformed

    private void EVENTOMUSICALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTOMUSICALActionPerformed
          tipoEvento = "musical";
        CrearEventoMusicalGUI create = new  CrearEventoMusicalGUI();
        create.setVisible(true);
        create.setLocationRelativeTo(null);
          this.setVisible(false);

    }//GEN-LAST:event_EVENTOMUSICALActionPerformed

    private void EVENTORELIGIOSOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTORELIGIOSOActionPerformed
          tipoEvento = "religioso"; 
        CrearEventoReligiosoGUI create = new  CrearEventoReligiosoGUI();
        create.setVisible(true);
        create.setLocationRelativeTo(null);
        this.setVisible(false);

    }//GEN-LAST:event_EVENTORELIGIOSOActionPerformed

    private void BACK2EVENTSMANAGERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BACK2EVENTSMANAGERActionPerformed
        EventsManager evs = new EventsManager();
        evs.setVisible(true);
        evs.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BACK2EVENTSMANAGERActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionTipoEventoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionTipoEventoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionTipoEventoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionTipoEventoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionTipoEventoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BACK2EVENTSMANAGER;
    private javax.swing.JButton EVENTODEPORTIVO;
    private javax.swing.JButton EVENTOMUSICAL;
    private javax.swing.JButton EVENTORELIGIOSO;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
